import { format, differenceInSeconds } from 'date-fns';

export interface Message {
  role: 'user' | 'assistant';
  content: string;
  timestamp: Date;
}

export interface ConversationMetadata {
  conversationId: string;
  startTime: Date;
  endTime?: Date;
  messageCount: number;
  userName?: string;
}

export function formatConversationDuration(startTime: Date, endTime?: Date): string {
  const end = endTime || new Date();
  const seconds = differenceInSeconds(end, startTime);
  
  if (seconds < 60) {
    return `${seconds}s`;
  }
  
  const minutes = Math.floor(seconds / 60);
  const remainingSeconds = seconds % 60;
  
  if (minutes < 60) {
    return remainingSeconds > 0 ? `${minutes}m ${remainingSeconds}s` : `${minutes}m`;
  }
  
  const hours = Math.floor(minutes / 60);
  const remainingMinutes = minutes % 60;
  return `${hours}h ${remainingMinutes}m`;
}

export function exportTranscriptAsTXT(messages: Message[]): string {
  const lines = messages.map(msg => {
    const time = format(msg.timestamp, 'HH:mm:ss');
    const role = msg.role === 'user' ? 'You' : 'Rari';
    return `[${time}] ${role}: ${msg.content}`;
  });
  
  return lines.join('\n\n');
}

export function exportTranscriptAsJSON(messages: Message[]): string {
  const formattedMessages = messages.map(msg => ({
    role: msg.role,
    content: msg.content,
    timestamp: msg.timestamp.toISOString()
  }));
  
  return JSON.stringify(formattedMessages, null, 2);
}

export function exportTranscriptAsPDF(
  messages: Message[], 
  metadata: ConversationMetadata
): void {
  // Create a printable HTML page
  const txt = exportTranscriptAsTXT(messages);
  const duration = formatConversationDuration(metadata.startTime, metadata.endTime);
  
  const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Rari Conversation Transcript</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
      max-width: 800px;
      margin: 40px auto;
      padding: 20px;
      line-height: 1.6;
    }
    .header {
      border-bottom: 2px solid #2596be;
      padding-bottom: 20px;
      margin-bottom: 30px;
    }
    .header h1 {
      margin: 0;
      color: #2596be;
    }
    .metadata {
      color: #666;
      font-size: 14px;
      margin-top: 10px;
    }
    .conversation {
      white-space: pre-wrap;
      font-family: monospace;
      font-size: 13px;
    }
    .footer {
      margin-top: 40px;
      padding-top: 20px;
      border-top: 1px solid #eee;
      text-align: center;
      color: #999;
      font-size: 12px;
    }
    @media print {
      body { margin: 0; }
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>Rari Conversation Transcript</h1>
    <div class="metadata">
      <div>Session ID: ${metadata.conversationId}</div>
      <div>Start Time: ${format(metadata.startTime, 'PPpp')}</div>
      ${metadata.endTime ? `<div>End Time: ${format(metadata.endTime, 'PPpp')}</div>` : ''}
      <div>Duration: ${duration}</div>
      <div>Messages: ${metadata.messageCount}</div>
    </div>
  </div>
  <div class="conversation">${txt.replace(/</g, '&lt;').replace(/>/g, '&gt;')}</div>
  <div class="footer">
    Generated by Exotiq.ai Rari AI Assistant
  </div>
</body>
</html>
  `;
  
  // Open in new window for printing
  const printWindow = window.open('', '_blank');
  if (printWindow) {
    printWindow.document.write(html);
    printWindow.document.close();
    printWindow.focus();
    
    // Trigger print dialog after content loads
    printWindow.onload = () => {
      printWindow.print();
    };
  }
}

export function downloadFile(content: string, filename: string, mimeType: string): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
