import { serve } from 'https://deno.land/std@0.168.0/http/server.ts';
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.39.3';
import { Resend } from 'https://esm.sh/resend@4.0.0';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders });
  }

  try {
    const { conversationId, recipientEmail } = await req.json();

    if (!conversationId || !recipientEmail) {
      throw new Error('Missing required parameters');
    }

    // Initialize Supabase client
    const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
    const supabaseKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
    const supabase = createClient(supabaseUrl, supabaseKey);

    // Get conversation details
    const { data: conversation, error: convError } = await supabase
      .from('rari_conversations')
      .select('*, rari_messages(*)')
      .eq('id', conversationId)
      .single();

    if (convError) throw convError;

    // Format messages for email
    const messages = (conversation.rari_messages || [])
      .sort((a: any, b: any) => new Date(a.timestamp).getTime() - new Date(b.timestamp).getTime())
      .map((msg: any) => {
        const time = new Date(msg.timestamp).toLocaleTimeString();
        const role = msg.role === 'user' ? 'You' : 'Rari';
        return `[${time}] ${role}: ${msg.content}`;
      })
      .join('\n\n');

    // Calculate duration
    const startTime = new Date(conversation.started_at);
    const endTime = conversation.ended_at ? new Date(conversation.ended_at) : new Date();
    const durationMinutes = Math.floor((endTime.getTime() - startTime.getTime()) / 60000);

    // Create HTML email
    const htmlContent = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
      line-height: 1.6;
      color: #333;
      max-width: 600px;
      margin: 0 auto;
      padding: 20px;
    }
    .header {
      background: linear-gradient(135deg, #2596be 0%, #1e7a9a 100%);
      color: white;
      padding: 30px;
      border-radius: 8px 8px 0 0;
      text-align: center;
    }
    .header h1 {
      margin: 0;
      font-size: 24px;
    }
    .metadata {
      background: #f5f5f5;
      padding: 20px;
      border-radius: 0 0 8px 8px;
      margin-bottom: 20px;
    }
    .metadata-item {
      margin: 8px 0;
      font-size: 14px;
    }
    .conversation {
      white-space: pre-wrap;
      background: #fff;
      padding: 20px;
      border: 1px solid #e0e0e0;
      border-radius: 8px;
      font-family: monospace;
      font-size: 13px;
    }
    .footer {
      margin-top: 30px;
      padding-top: 20px;
      border-top: 1px solid #e0e0e0;
      text-align: center;
      color: #999;
      font-size: 12px;
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>Rari Conversation Summary</h1>
  </div>
  
  <div class="metadata">
    <div class="metadata-item"><strong>Date:</strong> ${startTime.toLocaleString()}</div>
    <div class="metadata-item"><strong>Duration:</strong> ${durationMinutes} minutes</div>
    <div class="metadata-item"><strong>Messages:</strong> ${conversation.message_count}</div>
  </div>
  
  <div class="conversation">${messages.replace(/</g, '&lt;').replace(/>/g, '&gt;')}</div>
  
  <div class="footer">
    Generated by ExotIQ.ai Rari AI Assistant
  </div>
</body>
</html>
    `;

    // Initialize Resend with API key
    const resendApiKey = Deno.env.get('RESEND_API_KEY');
    
    if (!resendApiKey) {
      console.error('[Email Summary] RESEND_API_KEY not configured');
      return new Response(
        JSON.stringify({ 
          success: false,
          error: 'Email service not configured'
        }),
        {
          status: 500,
          headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        }
      );
    }

    const resend = new Resend(resendApiKey);
    
    // Send the email via Resend
    const { data: emailData, error: emailError } = await resend.emails.send({
      from: 'Rari AI <noreply@exotiq.ai>',
      to: [recipientEmail],
      subject: `Rari Conversation Summary - ${startTime.toLocaleDateString()}`,
      html: htmlContent,
    });

    if (emailError) {
      console.error('[Email Summary] Resend error:', emailError);
      return new Response(
        JSON.stringify({ 
          success: false,
          error: emailError.message || 'Failed to send email'
        }),
        {
          status: 500,
          headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        }
      );
    }

    console.log('[Email Summary] Email sent successfully:', emailData?.id);

    return new Response(
      JSON.stringify({ 
        success: true,
        message: 'Email sent successfully',
        emailId: emailData?.id
      }),
      {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      }
    );
  } catch (error: any) {
    console.error('[Email Summary] Error:', error);
    return new Response(
      JSON.stringify({ error: error.message }),
      {
        status: 500,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      }
    );
  }
});