// OFFLINE policy tests. Store fixtures do not establish SQL/RLS or provider parity.
import { describe, expect, it } from 'vitest';
import { assertReceiptBinding, requireBookingGrant, recoveryDisposition, safeGrantAudit, GrantAccessError } from '../../supabase/functions/_shared/external-booking/grants.ts';
import type { Principal } from '../../supabase/functions/_shared/external-booking/auth.ts';
const principal: Principal = { subject: 'subject-a', issuer: 'https://issuer.example.test', audience: 'https://api.example.test/v1', customerId: 'customer-a', clientId: 'client-a', tokenId: 'token-a', scopes: ['rental_requests:read', 'checkout:handoff'] };
const instant = Date.parse('2026-10-07T18:00:00Z');
const grant = { id: 'grant-a', issuer: principal.issuer, subject: principal.subject, clientId: principal.clientId, customerId: principal.customerId, operatorId: 'operator-a', bookingId: 'booking-a', actions: ['rental_requests:read', 'checkout:handoff'] as const, expiresAt: new Date(instant + 86400000).toISOString(), revokedAt: null, secretHash: 'not-a-bearer-secret' };
const target = { grantId: grant.id, operatorId: grant.operatorId, bookingId: grant.bookingId };
const receipt = { id: 'receipt-a', issuer: principal.issuer, subject: principal.subject, clientId: principal.clientId, customerId: principal.customerId, operatorId: grant.operatorId, quoteId: 'quote-a', termsHash: 'a'.repeat(64), action: 'rental_requests:create' as const, expiresAt: new Date(instant + 900000).toISOString(), consumedAt: null };
const binding = { operatorId: receipt.operatorId, quoteId: receipt.quoteId, termsHash: receipt.termsHash, action: receipt.action };
describe('offline grant ownership and recovery policy', () => {
  it('permits exact owner, tenant, booking and action', async () => { await expect(requireBookingGrant({ getGrant: async () => grant }, principal, target, 'checkout:handoff', new Date(instant))).resolves.toMatchObject({ id: grant.id }); });
  it.each([{ customerId: 'other' }, { subject: 'other' }, { issuer: 'https://other.test' }, { clientId: 'other' }])('conceals cross-principal substitution %j', async (override) => { await expect(requireBookingGrant({ getGrant: async () => grant }, { ...principal, ...override }, target, 'checkout:handoff', new Date(instant))).rejects.toMatchObject({ code: 'not_found' }); });
  it.each([{ operatorId: 'other' }, { bookingId: 'other' }, { grantId: 'other' }])('conceals cross-resource substitution %j', async (override) => { await expect(requireBookingGrant({ getGrant: async () => grant }, principal, { ...target, ...override }, 'checkout:handoff', new Date(instant))).rejects.toMatchObject({ code: 'not_found' }); });
  it('requires both access-token scope and grant action', async () => { await expect(requireBookingGrant({ getGrant: async () => ({ ...grant, actions: ['rental_requests:read'] }) }, principal, target, 'checkout:handoff', new Date(instant))).rejects.toMatchObject({ code: 'forbidden' }); await expect(requireBookingGrant({ getGrant: async () => grant }, { ...principal, scopes: ['rental_requests:read'] }, target, 'checkout:handoff', new Date(instant))).rejects.toMatchObject({ code: 'forbidden' }); });
  it.each([25, 71])('requires fresh customer authorization after %ih without changing hold fields', async (hours) => { const before = structuredClone(grant); const hold = { holdExpiresAt: '2026-10-08T18:00:00Z', ledger: 'unchanged' }; const later = new Date(instant + hours * 3600000); await expect(requireBookingGrant({ getGrant: async () => grant }, principal, target, 'checkout:handoff', later)).rejects.toMatchObject({ reason: 'grant_expired' }); expect(recoveryDisposition(grant, principal, target, later)).toBe('fresh_customer_authorization'); expect(grant).toEqual(before); expect(hold).toEqual({ holdExpiresAt: '2026-10-08T18:00:00Z', ledger: 'unchanged' }); });
  it('revocation takes precedence over expiry and old ID never refreshes', async () => { const revoked = { ...grant, revokedAt: new Date(instant).toISOString() }; const later = new Date(instant + 71 * 3600000); expect(recoveryDisposition(revoked, principal, target, later)).toBe('explicit_new_delegation'); await expect(requireBookingGrant({ getGrant: async () => revoked }, principal, target, 'rental_requests:read', later)).rejects.toBeInstanceOf(GrantAccessError); await expect(requireBookingGrant({ getGrant: async () => revoked }, principal, target, 'rental_requests:read', later)).rejects.toMatchObject({ reason: 'grant_revoked' }); });
  it('re-reads revocation every operation', async () => { let revokedAt: string | null = null; const store = { getGrant: async () => ({ ...grant, revokedAt }) }; await requireBookingGrant(store, principal, target, 'rental_requests:read', new Date(instant)); revokedAt = new Date(instant).toISOString(); await expect(requireBookingGrant(store, principal, target, 'rental_requests:read', new Date(instant))).rejects.toMatchObject({ reason: 'grant_revoked' }); });
  it('fails closed on store outage or corrupt expiry', async () => { await expect(requireBookingGrant({ getGrant: async () => { throw new Error('database secret'); } }, principal, target, 'rental_requests:read')).rejects.toMatchObject({ code: 'upstream_unavailable' }); await expect(requireBookingGrant({ getGrant: async () => ({ ...grant, expiresAt: 'bad' }) }, principal, target, 'rental_requests:read')).rejects.toMatchObject({ code: 'upstream_unavailable' }); });
  it('audit allowlist exposes no credentials, hashes, customer or subject', () => { expect(safeGrantAudit(grant, 'revoked')).toEqual({ grant_id: grant.id, operator_id: grant.operatorId, booking_id: grant.bookingId, action: 'revoked' }); });
});
describe('offline receipt policy: not transactional persistence evidence', () => {
  it('requires exact principal, client, quote, terms and action', () => { expect(() => assertReceiptBinding(receipt, principal, binding, new Date(instant))).not.toThrow(); });
  it.each([{ customerId: 'other' }, { subject: 'other' }, { clientId: 'other' }, { issuer: 'https://other.test' }, { operatorId: 'other' }, { quoteId: 'other' }, { termsHash: 'b'.repeat(64) }, { action: 'checkout:handoff' }])('denies substitution %j', (change) => { expect(() => assertReceiptBinding({ ...receipt, ...change }, principal, binding, new Date(instant))).toThrow(); });
  it('rejects consumed and expired receipts even if bearer reference is known', () => { expect(() => assertReceiptBinding({ ...receipt, consumedAt: new Date(instant).toISOString() }, principal, binding, new Date(instant))).toThrow(); expect(() => assertReceiptBinding(receipt, principal, binding, new Date(instant + 900000))).toThrow(); });
});
