import {expect,it} from 'vitest';import {SignJWT} from 'jose';
import {createHandoffExtension} from '../../supabase/functions/_shared/external-booking/handoff-routes.ts';
import {BookingApiError} from '../../supabase/functions/_shared/external-booking/errors.ts';
it('current provider action denial prevents a nonce lease and all provider calls despite valid customer read proof',async()=>{
 const now=Date.now(),resource='https://api.example.invalid/external-booking-api',origin='https://customer.example.invalid',key=new Uint8Array(32).fill(4),path='/v1/customer-handoffs/'+'a'.repeat(43)+'/resolve',body={action:'continue'},raw=JSON.stringify(body),bearer='signed-fixture',hash=async(v:string)=>Buffer.from(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v))).toString('hex'),calls:string[]=[],scopes:string[]=[];let providers=0;
 const principal={issuer:'https://issuer.example.invalid',subject:'renter',clientId:'hosted',audience:resource,tokenId:'fixture',scopes:['rental_requests:read'] as const},proof=await new SignJWT({provider_issuer:principal.issuer,provider_subject:principal.subject,client_id:'hosted',method:'POST',path:'/external-booking-api'+path,body_hash:await hash(raw),token_hash:await hash(bearer),csrf_hash:'b'.repeat(64),profile_email:'renter@example.invalid',profile_email_verified:true}).setProtectedHeader({alg:'HS256',typ:'exotiq-hosted-proof+jwt'}).setIssuer(origin).setAudience(resource).setIssuedAt(Math.floor(now/1000)).setExpirationTime(Math.floor(now/1000)+30).setJti('fixture-proof').sign(key);
 const route=createHandoffExtension({auth:{requirePrincipal:async(_req,scope)=>{scopes.push(scope);if(scope!=='rental_requests:read')throw new BookingApiError('forbidden');return principal;}},rpc:{rpc:async name=>{calls.push(name);return {data:{api_version:'v1',source_checked_at:new Date(now).toISOString(),ref:'owned-ref',operator_name:'Synthetic Operator',vehicle_name:'Synthetic Vehicle',action:'identity',status:'pending_documents',expires_at:new Date(now+60000).toISOString()},error:null};}},hosted:{frontendOrigin:origin,resource,bridgeKey:Buffer.from(key).toString('base64url'),hostedClientIds:['hosted']},now:()=>now,customerOrigin:origin,mode:'test',provider:{resolve:async()=>{providers++;throw new Error('Forbidden provider access');}}});
 await expect(route(new Request(resource+path,{method:'POST',headers:{authorization:'Bearer '+bearer,'X-Exotiq-Hosted-Proof':proof,origin},body:raw}),path,body)).rejects.toMatchObject({code:'forbidden'});
 expect(scopes).toEqual(['rental_requests:read','identity:handoff']);expect(calls).toEqual(['external_review_customer_handoff']);expect(providers).toBe(0);
});
