// Offline HTTP policy checks; actual PostgreSQL route checks use request-lab.
import {expect,it} from 'vitest';
import {createRequestExtension} from '../../supabase/functions/_shared/external-booking/request-routes.ts';
import {BookingApiError} from '../../supabase/functions/_shared/external-booking/errors.ts';
import {createRuntime} from '../../supabase/functions/external-booking-api/index.ts';
import {generateKeyPair,exportJWK,createLocalJWKSet,SignJWT} from 'jose';
const at=Date.parse('2026-10-07T18:00:00Z'),ref='test-ref';
const principal={issuer:'https://issuer.example.test',subject:'renter',clientId:'agent',audience:'https://api.example.test/external-booking-api',tokenId:'jwt',scopes:['rental_requests:create','rental_requests:read','checkout:handoff'] as const};
const input={quote_id:'33333333-3333-4333-8333-333333333333',consent_receipt_id:'44444444-4444-4444-8444-444444444444'};
const created={api_version:'v1',source_checked_at:new Date(at).toISOString(),ref,status:'pending_documents',next_action:'verify_identity',hold_expires_at:'2026-10-08T18:00:00Z',links:{status:`https://api.example.test/v1/rental-requests/${ref}`}};
const evidence={ref,source_checked_at:new Date(at).toISOString(),status:'pending_documents',authoritative:true,created_at:new Date(at).toISOString(),pickup_at:'2026-10-20T18:00:00Z',payment_due_at:null,identity_verified:false,operator_payment:{present:false,settled:false},exotiq_payment:{present:false,settled:false}};
function handler(rpc:(name:string,args:Record<string,unknown>)=>Promise<{data:unknown,error:unknown}>,auth=async()=>principal){return createRequestExtension({rpc:{rpc},auth:{requirePrincipal:auth},publicOrigin:'https://api.example.test',now:()=>at,sleep:async()=>{}});}
function req(method:string,path:string,headers:Record<string,string>={}){return new Request(`https://api.example.test${path}`,{method,headers});}
it('returns201 only for first atomic creation and200 for durable replay, same public body',async()=>{
 let calls=0;const run=handler(async(name,args)=>{expect(name).toBe('external_submit_rental_request_result');expect(args).toMatchObject({_issuer:principal.issuer,_subject:principal.subject,_client_id:'agent',_idempotency_key:'same-key-123456789'});return {data:{created:calls++===0,response:created},error:null};});
 for(const status of [201,200]){const r=await run(req('POST','/v1/rental-requests',{'Idempotency-Key':'same-key-123456789'}),'/v1/rental-requests',input);expect(r!.status).toBe(status);expect(await r!.json()).toEqual(created);}
});
it('rejects absent retry key/receipt and caller totals before mutation',async()=>{let calls=0;const run=handler(async()=>{calls++;return {data:null,error:null};});for(const [headers,body] of [[{},input],[{'Idempotency-Key':'same-key-123456789'},{...input,total:10}],[{'Idempotency-Key':'same-key-123456789'},{quote_id:input.quote_id}]] as const)await expect(run(req('POST','/v1/rental-requests',headers),'/v1/rental-requests',body)).rejects.toMatchObject({code:'invalid_input'});expect(calls).toBe(0);});
it('authenticates and reloads current grant even for matching conditional304 requests',async()=>{
 let reads=0,auths=0,deny=false;const run=handler(async()=>{reads++;return deny?{data:null,error:{message:'not_found'}}:{data:evidence,error:null};},async()=>{auths++;return principal;});
 const first=await run(req('GET',`/v1/rental-requests/${ref}`),`/v1/rental-requests/${ref}`,undefined);expect(first!.status).toBe(200);expect(first!.headers.get('Retry-After')).toBe('5');const tag=first!.headers.get('ETag')!;
 const second=await run(req('GET',`/v1/rental-requests/${ref}`,{'If-None-Match':tag}),`/v1/rental-requests/${ref}`,undefined);expect(second!.status).toBe(304);expect(await second!.text()).toBe('');expect(auths).toBe(2);expect(reads).toBe(2);
 deny=true;await expect(run(req('GET',`/v1/rental-requests/${ref}`,{'If-None-Match':tag}),`/v1/rental-requests/${ref}`,undefined)).rejects.toMatchObject({code:'not_found'});
});
it('changes the ETag on actual status changes, never confirms from intent IDs',async()=>{let current={...evidence};const run=handler(async()=>({data:current,error:null}));const first=await run(req('GET',`/v1/rental-requests/${ref}`),`/v1/rental-requests/${ref}`,undefined);current={...evidence,status:'requested'};const next=await run(req('GET',`/v1/rental-requests/${ref}`,{'If-None-Match':first!.headers.get('ETag')!}),`/v1/rental-requests/${ref}`,undefined);expect(next!.status).toBe(200);expect((await next!.json()).next_action).toBe('await_operator');});
it.each(['grant_expired','grant_revoked'])('verified owner %s receives recoveryLink, another owner receives404 withoutLink',async(code)=>{
 const run=handler(async()=>({data:null,error:{message:code}})),response=await run(req('GET',`/v1/rental-requests/${ref}`),`/v1/rental-requests/${ref}`,undefined);expect(response!.status).toBe(409);expect(response!.headers.get('Link')).toBe(`<https://api.example.test/v1/rental-requests/${ref}/grant-renewals>; rel="grant-renewal"`);expect((await response!.json()).code).toBe(code);
 const hidden=handler(async()=>({data:null,error:{message:'not_found'}}));await expect(hidden(req('GET',`/v1/rental-requests/${ref}`),`/v1/rental-requests/${ref}`,undefined)).rejects.toMatchObject({code:'not_found'});
});
it('partial settlement in reconciliation never publishes another checkout',async()=>{
 const raw={...evidence,status:'pending_payment',identity_verified:true,payment_due_at:'2026-10-07T20:00:00Z',reconciliation_pending:true,operator_payment:{present:true,settled:true}};
 const run=handler(async()=>({data:raw,error:null})),response=await run(req('GET',`/v1/rental-requests/${ref}`),`/v1/rental-requests/${ref}`,undefined),body=await response!.json();expect(body.next_action).toBe('await_reconciliation');expect(body.links.checkout_handoff).toBeUndefined();
});
it('does not publish a checkout capability until the14 resolver is concretely mounted',async()=>{let calls=0;const run=handler(async()=>{calls++;return {data:evidence,error:null};});expect(await run(req('POST',`/v1/rental-requests/${ref}/checkout-handoff`),`/v1/rental-requests/${ref}/checkout-handoff`,{})).toBeNull();expect(calls).toBe(0);});
it('retries entire atomic request on lock waits but never blindly retries transport ambiguity',async()=>{let calls=0;const run=handler(async()=>++calls<3?{data:null,error:{code:'55P03',message:'lock timeout'}}:{data:{created:true,response:created},error:null});expect((await run(req('POST','/v1/rental-requests',{'Idempotency-Key':'same-key-123456789'}),'/v1/rental-requests',input))!.status).toBe(201);expect(calls).toBe(3);const failed=handler(async()=>{throw Error('private upstream');});await expect(failed(req('POST','/v1/rental-requests',{'Idempotency-Key':'same-key-123456789'}),'/v1/rental-requests',input)).rejects.toBeInstanceOf(BookingApiError);});
it('mounts actual production request/status RPCs behind real signed JWT/introspection and correct scope challenges',async()=>{
 const keys=await generateKeyPair('ES256',{extractable:true}),resolver=createLocalJWKSet({keys:[{...await exportJWK(keys.publicKey),kid:'unit',alg:'ES256'}]});
 const provider={issuer:principal.issuer,resource:principal.audience,jwksUri:principal.issuer+'/jwks',metadataUrl:'https://api.example.test/.well-known/oauth-protected-resource',allowedHosts:['issuer.example.test','api.example.test','customer.example.test'],algorithms:['ES256'] as const,clientIds:['agent'],maxTokenLifetimeSeconds:600};
 const token=await new SignJWT({iss:provider.issuer,aud:provider.resource,sub:principal.subject,jti:'jwt',client_id:'agent',scope:principal.scopes.join(' '),iat:at/1000,nbf:at/1000,exp:at/1000+600}).setProtectedHeader({alg:'ES256',typ:'at+jwt',kid:'unit'}).sign(keys.privateKey);
 const calls:string[]=[];let first=true;const runtime=createRuntime({provider,introspectionUrl:provider.issuer+'/introspect',introspectionAuthorization:'Basic synthetic',supabaseUrl:'https://abcdefghijklmnopqrst.supabase.co',serviceKey:'synthetic',cursorKey:new Uint8Array(32),consentOrigin:'https://customer.example.test',browseEnabled:false},async(raw,init)=>{
  const url=new URL(String(raw)),name=url.pathname.split('/').at(-1)!;calls.push(name);return new Response(JSON.stringify(name==='introspect'?{active:true,iss:provider.issuer,aud:provider.resource,sub:principal.subject,jti:'jwt',client_id:'agent',scope:principal.scopes.join(' '),exp:at/1000+600}:name==='check_rate_limit'?true:name==='external_submit_rental_request_result_customer'?{created:first?(first=false,true):false,response:{...created,links:{status:JSON.parse(String(init?.body))._public_origin+'/v1/rental-requests/'+ref}}}:name==='external_read_rental_request'?evidence:null));
 },{keyResolver:resolver,now:()=>at});
 for(const status of [201,200]){const response=await runtime(new Request(provider.resource+'/v1/rental-requests',{method:'POST',headers:{authorization:`Bearer ${token}`,'content-type':'application/json','Idempotency-Key':'same-key-123456789'},body:JSON.stringify(input)}));expect(response.status).toBe(status);expect(await response.json()).toEqual({...created,links:{status:provider.resource+'/v1/rental-requests/'+ref}});}
 const read=await runtime(new Request(provider.resource+`/v1/rental-requests/${ref}`,{headers:{authorization:`Bearer ${token}`}}));expect(read.status).toBe(200);expect((await read.json()).links.status).toBe(provider.resource+'/v1/rental-requests/'+ref);expect(calls.filter(name=>name==='introspect')).toHaveLength(3);
 for(const [path,scope] of [['/v1/rental-requests','rental_requests:create'],[`/v1/rental-requests/${ref}`,'rental_requests:read']] as const){const response=await runtime(new Request(provider.resource+path,{method:path.endsWith(ref)?'GET':'POST',headers:{'content-type':'application/json','Idempotency-Key':'same-key-123456789'},...(path.endsWith(ref)?{}:{body:JSON.stringify(input)})}));expect(response.status).toBe(401);expect(response.headers.get('WWW-Authenticate')).toContain(`scope="${scope}"`);}
});
