// Offline request adapter policies. Real atomicity/concurrency runs in request-lab.
import { expect, it } from 'vitest';
import { submitRentalRequest, SupabaseRequestStore } from '../../supabase/functions/_shared/external-booking/requests.ts';
const principal = { issuer: 'https://issuer.example.test', subject: 'renter', customerId: '11111111-1111-4111-8111-111111111111', operatorId: '22222222-2222-4222-8222-222222222222', audience: 'https://api.example.test/v1', clientId: 'client-a', tokenId: 'token-a', scopes: ['rental_requests:create'] as const };
const input = { quote_id: '33333333-3333-4333-8333-333333333333', consent_receipt_id: '44444444-4444-4444-8444-444444444444' };
const response = { api_version: 'v1', source_checked_at: '2026-10-07T18:00:00Z', ref: 'agent-test-request', status: 'pending_documents', next_action: 'verify_identity', hold_expires_at: '2026-10-08T18:00:00Z', links: { status: 'https://api.example.test/v1/rental-requests/agent-test-request' } };
it('calls the durable transaction, never an in-memory booking implementation', async () => { let args; const store = new SupabaseRequestStore({ rpc: async (name, supplied) => { expect(name).toBe('external_submit_rental_request'); args = supplied; return { data: response, error: null }; } }, 'https://api.example.test'); await expect(submitRentalRequest(input, 'retry-key-123456789', principal, store)).resolves.toEqual(response); expect(args).toMatchObject({ _quote_id: input.quote_id, _receipt_id: input.consent_receipt_id, _customer_id: principal.customerId, _client_id: principal.clientId }); });
it('retries the whole transaction on inventory serialization, bounded with backoff', async () => { let attempts = 0; const delays: number[] = []; const store = new SupabaseRequestStore({ rpc: async () => ++attempts < 3 ? { data: null, error: { code: '40001', message: 'inventory_retry' } } : { data: response, error: null } }, 'https://api.example.test', { sleep: async (ms) => { delays.push(ms); }, random: () => 0 }); await expect(submitRentalRequest(input, 'retry-key-123456789', principal, store)).resolves.toEqual(response); expect(attempts).toBe(3); expect(delays).toEqual([25, 50]); });
it('does not blindly retry ambiguous transport failure; caller retries same durable key', async () => { let attempts = 0; const store = new SupabaseRequestStore({ rpc: async () => { attempts++; throw Error('network secret'); } }, 'https://api.example.test'); await expect(submitRentalRequest(input, 'retry-key-123456789', principal, store)).rejects.toMatchObject({ code: 'upstream_unavailable' }); expect(attempts).toBe(1); });
it.each([{}, { ...input, consent_receipt_id: undefined }, { ...input, totals: 1 }])('denies missing consent and client totals %j', async (bad) => { await expect(submitRentalRequest(bad, 'retry-key-123456789', principal, { create: async () => response })).rejects.toMatchObject({ code: 'invalid_input' }); });
it('requires resolved tenant customer and write scope', async () => { for (const change of [{ customerId: undefined }, { operatorId: undefined }, { scopes: ['catalog:read'] }]) await expect(submitRentalRequest(input, 'retry-key-123456789', { ...principal, ...change }, { create: async () => response })).rejects.toMatchObject({ code: 'unauthorized' }); });
it('allows only reviewed public response shape and strips no legacy token implicitly', async () => { await expect(submitRentalRequest(input, 'retry-key-123456789', principal, { create: async () => ({ ...response, confirmation_token: 'secret' }) })).rejects.toMatchObject({ code: 'upstream_unavailable' }); });
