import { beforeAll, beforeEach, expect, it, vi } from 'vitest';
import { runRequestLab } from './helpers/request-lab.ts';
import { handler } from './helpers/edge-server.ts';
import { setClient } from './helpers/edge-supabase.ts';
const mocks=vi.hoisted(()=>({allowed:true,turnstile:true,send:vi.fn(async(_args:Record<string,unknown>)=>({message_id:'sink-message'}))}));
vi.mock('../../supabase/functions/_shared/rateLimit.ts',()=>({checkRateLimit:async()=>mocks.allowed,clientIp:()=> 'synthetic-ip',verifyTurnstile:async()=>({ok:mocks.turnstile})}));
vi.mock('../../supabase/functions/_shared/rentEmail.ts',()=>({sendRenterEmail:mocks.send,resolveRenterReplyTo:()=> 'support@example.invalid'}));
let calls:Array<{name:string,args:Record<string,unknown>}>=[];
beforeAll(async()=>{vi.stubGlobal('Deno',{env:{get:(name:string)=>name==='RENTER_APP_ORIGIN'?'https://renter.example.invalid':'synthetic-local-configuration'}});await import('../../supabase/functions/rent-create-booking/index.ts');runRequestLab('setup.mjs');});
beforeEach(()=>{calls=[];mocks.allowed=true;mocks.turnstile=true;mocks.send.mockClear();setClient({rpc:async(name:string,args:Record<string,unknown>)=>{calls.push({name,args});if(name==='public_vehicle_quote')return{data:[{daily_rate_cents:10000,operator_total_cents:20000,deposit_cents:0,platform_fee_cents:100,protection_total_cents:200,state_fee_cents:100,processing_fee_cents:100,operator_tax_cents:0}],error:null};return{data:[{booking_ref:'agent-test-legacy',confirmation_token:'11111111-1111-4111-8111-111111111111',status:args._initial_status}],error:null};},from:(table:string)=>{if(table==='identity_verifications')throw Error('typed email identity lookup must not execute');const chain={select:()=>chain,eq:()=>chain,maybeSingle:async()=>({data:table==='teams'?{name:'agent-test Operator',timezone:'America/New_York',currency:'USD'}:{start_date:new Date(Date.now()+86400000).toISOString(),pickup_location:'agent-test pickup',vehicle_name:'agent-test Vehicle'}})};return chain;}});});
function body(extra:Record<string,unknown>={}){return{team_slug:'agent-test-miami',vehicle_slug:'agent-test-vehicle',start_date:new Date(Date.now()+30*86400000).toISOString().slice(0,10),end_date:new Date(Date.now()+32*86400000).toISOString().slice(0,10),pickup_time:'10:00 AM',return_time:'11:00 AM',protection:'premium',driver:{name:'agent-test Renter',email:'agent-test-renter@example.invalid',phone:'2025550101'},...extra};}
const request=(input:unknown)=>new Request('https://legacy.example.invalid',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(input)});
it('actual legacy handler retains guest input and explicit return-time but never grants identity from email',async()=>{const response=await handler(request(body()));expect(response.status).toBe(200);expect(await response.json()).toMatchObject({status:'pending_documents',identity_verified:false});expect(calls[1]).toMatchObject({name:'create_marketplace_booking',args:{_initial_status:'pending_documents',_return_time:'11:00 AM'}});expect(mocks.send).toHaveBeenCalledOnce();expect(mocks.send.mock.calls[0][0]).toMatchObject({idempotencyKey:'request-agent-test-legacy'});});
it('keeps Turnstile and rate limiting ahead of any booking mutation',async()=>{mocks.turnstile=false;expect((await handler(request(body()))).status).toBe(400);expect(calls).toHaveLength(0);mocks.allowed=false;expect((await handler(request(body()))).status).toBe(429);expect(calls).toHaveLength(0);});
it.each(['quote_id','consent_receipt_id','grant_id','delegation','customer_id'])('rejects delegated field %s on guest contract',async(field)=>{expect((await handler(request(body({[field]:'untrusted'})))).status).toBe(400);expect(calls).toHaveLength(0);});
it('uses actual SQL verified tenant identity predicate and preserved14/17/18/default caller signatures',()=>{expect(runRequestLab('lab.mjs','compatibility-check.sql')).toContain('ROLLBACK');});
